steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["test"]
  # build docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/mastende-backend/receipts", "."]
  # push docker image into image registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/mastende-backend/receipts"]
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/mastende-backend/receipts:latest
      - --location=europe-west4-a
      - --cluster=mastende-cluster
