apiVersion: v1
kind: Service
metadata:
  name: receipts
spec:
  type: LoadBalancer
  selector:
    app: receipts
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: receipts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipts
  template:
    metadata:
      labels:
        app: receipts
    spec:
      containers:
        - name: receipts
          # Replace $GCLOUD_PROJECT with your project ID
          image: gcr.io/mastende-backend/receipts:latest
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
